# Generated by Django 5.1.4 on 2025-02-20 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fresh_Fruits_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruits',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Fresh_Fruits_app.shop_reg'),
        ),
    ]
