# Generated by Django 5.1.4 on 2025-02-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fresh_Fruits_app', '0002_fruits_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='totalprice',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
