# Generated by Django 5.1.4 on 2025-02-22 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fresh_Fruits_app', '0003_booking_totalprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='emoji_reaction',
            new_name='reaction',
        ),
    ]
