# Generated by Django 5.1.4 on 2025-02-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fresh_Fruits_app', '0004_rename_emoji_reaction_feedback_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Processing', max_length=50, null=True),
        ),
    ]
